FROM centos:latest
RUN yum install openssh -y
RUN yum install openssh-server -y
RUN yum install openssh-clients-8.0p1-5.el8.x86_64 -y
RUN echo "root:{{  passwd_container  }}" | chpasswd
RUN mkdir -p /root/.ssh
RUN ssh-keygen -A
EXPOSE 22
CMD  ["/usr/sbin/sshd","-D"]


